# 导言

::: {.callout-important}
## 学习目标

1. 宏观经济学的两个研究对象
2. 模型、研究过程
3. 简要的历史
:::


宏观经济学关心的众多经济总体的共同作用的总效应，具体来说就是，经济增长和经济周期。经济增长或者长期增长是一国长期的生产能力和平均生活水平的提高，而经济周期指的是总体经济活动的短期波动，或经济繁荣于经济衰退。

本书或者主流宏观经济学家都将宏观经济分析建立在微观经济学原理的基础之上（也就是从各个主体出发来研究总体反映），当然这需要一些努力（宏观经济学家也是经过不断思考才确定了这一种研究范式），但能够更加清晰的理解经济运行和把握重要的外生变量对经济的影响（如何提高经济增长）。

::: {.callout-note}
## 经济研究的主要步骤

1. Step 1：数据搜集和经验特征事实的概括
2. Step 2：建立模型
3. Step 3：模型检验、实证分析
:::

事实上，这三个步骤是相互联系的，是从问题到模型再到技术的过程！！！数学只是最后的一步，而不是最重要的、最初始的一步。

接下来我们从这三个角度来总体介绍一下后续工作中重要的概念和思想。
:::

国内生产总值能够反映总体经济活动随着时间的变化。更一般的，根据通货膨胀和人口增长因素的调整后的总产出衡量指标，实际人均GDP，能够更加真实反映一个国家的平均生活水平的变化。

::: {.callout-note}
## 国内生产总值 Gross Domestic Product (GDP)

一国在指定时间跨度内的**境内**生产的产品和服务的数量
:::

我们通常可以对研究的变量进行取对数操作，绘制折线图，观察其变化率。另一方面，对经济时间序列采取分割的方式来分析长期趋势和短期波动，常用的方法有：

- Log-linear Detrending
- Hodrick-Prescott Filter
- Crafts-Leybourne-Mills Model

我们一般认为长期趋势是最优化下的**潜在产出**，然而一些意外状况造成了产出的波动，形成了短期的经济波动。

根据这两种方法，基于国内生产总值或者其他总体层面的指标，能够让我们能够对一定时间内的总体经济状况有一定的把握，同时也可以概括出一定的经验特征事实（我们看到的都是历史的经验）。这里不在赘述关于美国和中国过去几十年的经济增长和经济周期的事实。

同时，一些基本的疑问也随之而来，他们驱动着一代又一代的经济学家对他们所处的时代的经济运行机制做出解释：

1. 什么导致了持续的经济增长
2. 经济增长是不是永无止境？
3. 为改变经济增长率，政府能够或应该做些什么
4. 经济周期是什么？是不是可以避免？
5. 大萧条和二战期间的剧烈波动是非会重现
6. 政府应不应该干预经济？

经济学的最终目的是建立关于经济运行的理论。相比于自然科学，随机可控实验对于经济学特别是宏观经济学来说是不现实的，模型是经济学家开展理论研究的最主要范式。从经验特征事实到经济模型是最重要的一步，这考验的是经济学家对经济运行的理解和对经济变量之间关系的把握，简而言之就是“经济学直觉”。故而，我们只能介绍建立模型的一般步骤：

1. 原料：变量的选取--对现实简化
2. 特征：静态？不确定性？
3. 联系：等式的设定、稳态的寻找：数理刻画和描述：消费者（偏好和商品，边际效用理论）、企业（技术资源，要素投入理论）、政府；最优化、均衡条件

::: {.callout-note}
## 理性预期革命

卢卡斯批判：只有认真对待微观经济行为，宏观经济政策分析才富有意义。

事实上，政府的政策不是想当然的改变着宏观经济变量，只有这些政策对微观经济主体的行为有所影响，才能够对总体经济产生影响。这也是为什么我们要从微观经济学的基础出发来研究宏观经济学的原因。
:::

通过对厂商和消费者在两个市场上的行为——劳动力市场（时间）、消费市场（商品）——的分析，我们旧可以得到一个简单的宏观经济模型，这个模型可以解释一些宏观经济现象，如失业率、通货膨胀率等。通常而言，我们假定：

1. 消费者最大化生命周期效用
2. 企业最大化利润
3. 信贷市场最大化利润（仅仅？）
4. 政府最大化社会福利（选民的争取？）

最后我们介绍一些宏观经济学的不同学派，一般来说对于经济增长的研究上宏观经济学的分期相对较少，但是正对经济周期凯恩斯主义和非凯恩斯主义的经济学家之间存在着教导的分歧。

- 古典和新古典：“看不见的手”
- 凯恩斯主义：“看得见的手”
- 货币主义：货币的性质
- 新兴古典：理性预期革命
- 新凯恩斯

对于经济周期理论：


- 凯恩斯主义
  - 传统：工资和价格的黏性，政府的财政和货币政策矫正私人市场的无效率
  - 新凯恩斯思想
    - 协调失效：经济的失衡来源于悲观情绪
    - 新凯恩斯主义经济学：DSGE模型
- 非凯恩斯主义：旨在熨平经济周期的政府政策，乐观来说无效，悲观来说有害
::: {.callout-tip}
## 小结

1. 现代宏观经济学依靠微观经济学原理构建模型、研究长期增长与经济周期
2. 一般来说，经济长期呈现增长趋势，并且围绕长期趋势呈现周期性波动
3. 主要问题：长期增长和经济周期的原因和政府政策在影响经济方面的恰当作用
4. 经济学家通过建立模型来解释经济现象，既要简化又要能够体现问题的各个关键特征
5. 消费者和企业面临既定约束的情况下实现最优化，同时消费者和企业的行为在均衡时是一致的。
6. 经济周期理论有着较大分歧
:::
