# 衡量

::: {.callout-important}
## 学习目标
1. 数量指数和价格指数的不同衡量
2. GDP的三种衡量
3. 价格指数和隐含GDP价格缩减指数
:::

基于模型的经济学研究只能说明，逻辑和数理上的正确。但是，对现实经济现象的解释才是经济学的最终目的。因此，我们需要对模型的预测能力进行检验。一般来说，我们使用计量经济学知识进行实证检验。但无论怎么说，对于经济体中经济活动的衡量都是第一步。

## 产出

正如前文所说，GDP是衡量总体经济活动的重要指标。这里我们细致讨论名义和实际GDP的计算。

::: {.callout-warning}
## GDP

1. 最终产出，**而非投入**
2. 地域为限制，**一个国家的境内；不是所有国民**
3. 最后的产出用货币计价，**而非真实价格**
4. 仅关注市场上的商品和服务，**而不关注家庭劳作和灰色地带交易**
5. 仅关注生产，**二手交易不计入（但服务计入）**
6. 包括公共商品和服务，**但不包括环境损失**

国民生产总值是国内生产要素创造的产出价值，无论生产是不是在该国境内。 $GNP = GDP + NFP$
:::

### 计算GDP的三种方法

- 产出法：产品的增加值
- 支出法：$C+I+G+(X-M)$
- 收入法：税后工资、税后利润、投资、税

产出法的关键是对每个主体找到其最终产品并且计算增加值，其中政府的增加值是其支出也就是政府雇员的工资。当出现存货投资时，仅仅生产者的产出增加。

支出法只要分主体考虑其支出即可：**消费支出、投资支出、政府支出、净出口**。当出现存货投资的时候，要理解存货首先是一个商品被产出并且处于出清的市场，所以如果一个生产者想要将其留下了作为下一期的存货，就首先要购买他（实际是购买生产他的生产力）。如果增加了300元的存货投资，消费支出并不会变，同时投资支出增加。

收入法的关键是理解政府的收入是税收，消费者的收入是工资收入和利息收入的加总，厂商的税后利润是商品价值减去工资减去利息减去中间产品成本减去税款（并不一定要卖掉）。同样的当出现存货投资时候不能理解为厂商的收入减少（即使其没有在当前的市场上、或者说被厂商回购了）。

### 名义GDP和实际GDP

名义GDP在现价基础上计算，实际GDP在基准年的固定价格上计算。实际GDP使得不同时期不同国家之间的国内生产总值能够进行比较。

实际GDP的衡量使用基年的价格乘以，结果同基年的选择有很大的关系，采取不同基年使得价格波动被引入。一般来说，采取链式加权的方式来避免，这种方法采用费雪指数来表示实际GDP$g_c = \sqrt{g_1,g_2}$。但是，即使消除了相对价格的变化，商品质量的变化被忽略了，并且难以正确处理新商品的出现。

::: {.callout-note}
## 各国实际GDP比较与宾大效应

事实上，比较各国的实际GDP是十分困难的：

1. 数据的质量
2. 同样商品在不同国家的价值量是不同的（即使换算到同一货币单位）

对于各国的商品价格，倘若观察到$P = eP^{*}$就意味着购买力平价。但是，我们通常会观察到 $P > e P^{*}$。

宾大效应指出了各国间的价格和汇率数据之间的规律——按照汇率调整后，高收入国家的价格通常比低收入国家低。《宾大世界统计》中的数据据此进行了调整，以供更加准确的比较
:::

## 价格水平的衡量

### 价格指数

价格指数是一定商品和服务价格的固定加权平均结果，根据商品和服务的属性，常见的价格指数分为采购经理价格指数（RPI）、消费者价格指数（CPI）、生产物价指数。这里我们主要关心消费者价格指数（CPI），将普通消费者基年购买的代表性商品的消费额为权重 $\frac{\sum p_1q_0}{\sum p_0q_0 } \times 100 = \sum \frac{p_1}{\sum p_0 q_0 } q_0 \times 100$

$$
\text{当年CPI} = \frac{\text{按当年价格计算的基年消费额}}{\text{按基年价格计算的基年消费额} } \times 100
$$

但是它只包括由消费者购买的商品或者服务。

### 隐含GDP价格缩减指数

$$
\text{隐含GDP价格缩减指数} =  \frac{\text{名义GDP}}{\text{实际GDP} } \times 100
$$

事实上，相当于$\frac{\sum p_1 q_1}{\sum p_0q_1} \times 100$

## 储蓄和财富

$S =  Y - C = T(\text{tax revenue}) - G(\text{government consumption})$

投资储蓄恒等式：$S = I + (CA)$，开放经济还要考虑经常账户余额（CA）

值得注意的是，投资是一个流量，财富是存量。

## 劳动力市场

$$
\text{人口} = \underbrace{\underbrace{\text{就业}+\text{正在寻找（失业）}}_{\text{劳动力人口}} + \text{不寻找工作且无业} }_{\text{适龄劳动力}} + 老人孩子等
$$

常见的指标有：

$$
\text{失业率} = \frac{\text{失业人数}}{\text{劳动力人口}}
$$

$$
\text{参与率} = \frac{\text{劳动力人口}}{\text{适龄劳动力人口}}
$$

$$
\text{就业——人口比率} = \frac{就业人数}{适龄劳动力人口 }
$$

一方面，失业率能够反映劳动力市场的紧张程度，以及潜在的工人找到工作的难度。另一方面失业率能够作为衡量经济福利的间接指标，让我们了解财富分配的情况。但是需要注意的是，失业率并不能体现工人寻找工作的强度（寻找工作花费的时间）所以对劳动力市场紧张程度的反映有偏。同时，由于没有考虑边缘劳动力——不积极寻找工作但是提供一份工作就会接受的潜在工人，他们可能失去了信心——在放映经济福利时也会有偏差。

## 其他

- 资本市场
- 国际市场

::: {.callout-tip}
## 小结

1. GDP的三种衡量方法
2. GDP遗漏了家务劳动和地下经济
3. 需要考虑名义GDP中有多少由通货膨胀造成的，实际GDP中多少是有用的。实际GDP面领着：1）相对价格的变动（链式加权计算。2）商品质量和性能随着时间的推移的变化.3）新商品的出现
4. 适龄劳动力由就业者、失业者（积极寻找工作的人）、未纳入劳动力人口的人组成。失业率有时用作反映劳动力市场的紧张程度的指标，但是在解释时需要谨慎
:::