# 经济周期的衡量

::: {.callout-important}
## 学习目标

1. GDP波动的规律性
2. GDP同其他经济变量的联动特征
3. 季节调整
4. 关键的经济周期事实

:::

经济周期相当无规律，我们无法预测GDP的变化。但是，通过观察宏观经济变量之间的联动，经济周期尤其自身的规律性，比如GDP的下降通常意味着较高的失业率。通过对于这些宏观变量数据之间的分析，能够为后续我们处理模型变量之间的关系提供一些启示。

## 经济周期

GDP偏离趋势的部分代表着经济周期活动。我们能够观察到的是GDP中有着高峰、繁荣和低谷、萧条。高峰是对趋势较大的正偏离，低谷是对趋势较大的负偏离。高峰和低谷往往就是拐点，意味着经济周期的转折。波幅是一次经济周期当中对于趋势项的最大偏离。每年中经济周期出现高峰的次数被称为经济周期的频率。

对于经济周期的观测，我们发现其唯一的规律性就是对实际GDP趋势的偏离具有着持续性。除此之外：

- 很不稳定
- 幅度不稳定
- 频率不稳定

故而对于GDP的趋势偏离预测是非常困难的。同时经济衰退和繁荣的持续时间和强度也是难以在事前预测的。单凭过去GDP的数据，我们无法预测未来的GDP。幸运的是，我们可以通过观察其他经济变量的变化来预测GDP的变化，他们表现出了比较强的联动关系。

## 联动

宏观经济学家关注单个宏观经济变量同实际GDP之间的联动：

- 顺周期：趋势偏离和实际GDP的趋势偏离正相关
- 逆周期：趋势偏离和实际GDP的趋势偏离负相关
- 非周期

我们将经济变量的趋势偏离作为时间序列处理，通过相关系数来判断其相关关系。

同时，宏观经济数据当中的滞后和先行关系是重要的：倘若某个宏观经济变量有助于预测实际GDP的未来走向则为先行变量；倘若实际GDP有助于预测某个宏观经济变量的未来走向则为滞后变量。当然，不滞后也不先行的变量则是一致变量。

另一方面，宏观经济变量偏离趋势的变动程度也是值得关注的。有一些经济变量十分敏感，其波动幅度远远大于实际GDP的波动幅度。通过计算偏离趋势的百分比标准差来衡量经济变量周期性变动。

故而，当在经济周期这一范畴中思考某一经济变量时，我们应当关注的是：

1. 顺周期还是逆周期的
2. 先行变量还是滞后变量
3. 比实际GDP的变化幅度大还是小


## 联动总结

||周期性|先行、滞后|相对于GDP的可变性|
|:--|:--|:--|:--|:--|
|消费|顺周期 |同步 | 较小|
|投资|顺周期 |同步 | **较大**|
|价格水平|**逆周期** |同步 |较小 |
|货币供给|顺周期 |先行 | 较小|
|就业 |顺周期 |**滞后** | 较小|
|实际工资 |顺周期 |？ | ？|
|平均劳动生产率 |顺周期 |同步 |较小 |

价格水平是逆周期的（存在反向菲利普斯曲线），同步、变化程度小于GDP的变量

货币供给是顺周期的，先行、变化程度同GDP差不多的变量。弗里德曼认为货币供给往往发生在实际GDP的变化之前这个事实意义重大。

就业是顺周期的、滞后、变化程度小于GDP的变量。对于实际工资，宏观经济学家们的意见不一。平均劳动生产率是顺周期、同步、变化幅度小于实际GDP的变量。

## 季节调整

通过观察历史信息来进行季节调整，提出可预料的季节成分。比如春节的支出较高对于货币供给的影响。

在宏观经济研究中的大多数数据都需要通过季节调整。    

::: {.callout-tip}
## 小结

1. GDP围绕其趋势的波动是非规律的。尽管实际GDP的趋势偏离是持续的，但是其波幅和频率没有观察到由任何规律。
2. 我们主要关注：顺周期？同步？与实际GDP相比变动幅度？
:::